import React from 'react'

export default function CppTutorial() {
  return (
    <div>
        <h3>C++ tutorial</h3>
        <p>C++ is a general-purpose programming language created by Danish computer scientist Bjarne Stroustrup as an extension of the C programming language, or "C with Classes". The language has expanded significantly over time, and modern C++ now has object-oriented, generic, and functional features in addition to facilities for low-level memory manipulation. It is almost always implemented as a compiled language, and many vendors provide C++ compilers, including the Free Software Foundation, LLVM, Microsoft, Intel, Oracle, and IBM, so it is available on many platforms.</p>
        <img src="../../res/cpp.png" width='400px' height='400px'></img>
        <h4>Philosophy</h4>
        <ul>
            <li>It must be driven by actual problems and its features should be immediately useful in real world programs.</li>
            <li>Every feature should be implementable (with a reasonably obvious way to do so).</li>
            <li>Programmers should be free to pick their own programming style, and that style should be fully supported by C++.</li>
            <li>Allowing a useful feature is more important than preventing every possible misuse of C++.</li>
            <li>It should provide facilities for organising programs into separate, well-defined parts, and provide facilities for combining separately developed parts.</li>
            <li>No implicit violations of the <a href="https://en.wikipedia.org/wiki/Type_system" title="Type system">type system</a> (but allow explicit violations; that is, those explicitly requested by the programmer).</li>
            <li>User-created types need to have the same support and performance as built-in types.</li>
            <li>Unused features should not negatively impact created executables (e.g. in lower performance).</li>
            <li>There should be no language beneath C++ except assembly language.</li>
            <li>C++ should work alongside other existing programming languages, rather than fostering its own separate and incompatible programming environment.</li>
            <li>If the programmer's intent is unknown, allow the programmer to specify it by providing manual control.</li>
        </ul>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mauris rhoncus aenean vel elit scelerisque mauris pellentesque pulvinar. Semper quis lectus nulla at volutpat diam. Elementum sagittis vitae et leo duis ut diam. Orci sagittis eu volutpat odio facilisis. Nibh praesent tristique magna sit amet purus. Mattis nunc sed blandit libero volutpat sed cras. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit. Placerat in egestas erat imperdiet sed euismod. Amet purus gravida quis blandit turpis cursus in hac habitasse. Id semper risus in hendrerit gravida rutrum. Imperdiet proin fermentum leo vel orci porta non pulvinar neque. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Dapibus ultrices in iaculis nunc sed augue lacus. Montes nascetur ridiculus mus mauris vitae ultricies. Ante in nibh mauris cursus mattis molestie a iaculis at. Diam phasellus vestibulum lorem sed risus ultricies tristique.</p>
<p>Elit pellentesque habitant morbi tristique senectus. Nunc congue nisi vitae suscipit tellus mauris a diam maecenas. Non nisi est sit amet facilisis. Vulputate ut pharetra sit amet. Velit euismod in pellentesque massa. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Porttitor eget dolor morbi non. Libero enim sed faucibus turpis in eu mi. Tincidunt praesent semper feugiat nibh sed pulvinar. Facilisis sed odio morbi quis commodo odio aenean sed. Non consectetur a erat nam at lectus urna duis convallis. Vivamus at augue eget arcu dictum varius duis at. Lacinia at quis risus sed. Id aliquet lectus proin nibh nisl. Mauris ultrices eros in cursus turpis massa tincidunt. Tellus at urna condimentum mattis pellentesque id nibh tortor. Urna molestie at elementum eu.</p>
<p>Etiam sit amet nisl purus in mollis nunc sed. Amet justo donec enim diam vulputate ut. Nibh sed pulvinar proin gravida. Scelerisque varius morbi enim nunc. Nisl purus in mollis nunc sed. Mi proin sed libero enim sed faucibus turpis in eu. Orci ac auctor augue mauris. Urna nunc id cursus metus aliquam eleifend mi in. Sagittis id consectetur purus ut. Id consectetur purus ut faucibus pulvinar elementum. Ultrices in iaculis nunc sed augue lacus. Turpis massa tincidunt dui ut ornare lectus sit amet. Tempor orci eu lobortis elementum nibh tellus molestie. Posuere urna nec tincidunt praesent. Nisi est sit amet facilisis magna.</p>
<p>Blandit turpis cursus in hac habitasse. A lacus vestibulum sed arcu non odio euismod lacinia at. Commodo quis imperdiet massa tincidunt. Posuere morbi leo urna molestie. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Nibh cras pulvinar mattis nunc sed blandit libero volutpat sed. Et pharetra pharetra massa massa. Duis convallis convallis tellus id interdum velit laoreet id. Felis bibendum ut tristique et egestas. Nisi lacus sed viverra tellus in hac habitasse. Ac odio tempor orci dapibus ultrices in iaculis. Nunc consequat interdum varius sit. Varius vel pharetra vel turpis nunc. Nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Pellentesque habitant morbi tristique senectus et netus. Eget nunc scelerisque viverra mauris in aliquam.</p>
<p>Nulla at volutpat diam ut venenatis tellus in metus vulputate. Amet nisl suscipit adipiscing bibendum est ultricies. Iaculis nunc sed augue lacus viverra vitae congue eu. Lacus laoreet non curabitur gravida arcu. Augue mauris augue neque gravida in fermentum. Quam lacus suspendisse faucibus interdum posuere. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Quisque non tellus orci ac. Euismod lacinia at quis risus sed vulputate odio ut. Morbi quis commodo odio aenean. Arcu cursus vitae congue mauris. Tristique senectus et netus et malesuada fames. Lacinia at quis risus sed. Egestas purus viverra accumsan in. Cras sed felis eget velit aliquet sagittis.</p>
<p>In vitae turpis massa sed. Varius morbi enim nunc faucibus a pellentesque sit amet. Netus et malesuada fames ac turpis. Vel quam elementum pulvinar etiam non quam. Duis ut diam quam nulla porttitor massa id. Aliquam ultrices sagittis orci a. At tellus at urna condimentum mattis. Sed ullamcorper morbi tincidunt ornare massa eget egestas. Eget nullam non nisi est sit. Lobortis feugiat vivamus at augue eget arcu dictum varius. Nibh cras pulvinar mattis nunc sed blandit libero volutpat sed. Scelerisque fermentum dui faucibus in ornare quam viverra.</p>
<p>Sit amet nulla facilisi morbi tempus. Eu lobortis elementum nibh tellus molestie nunc. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Sed tempus urna et pharetra pharetra massa massa ultricies. Lobortis elementum nibh tellus molestie nunc. Libero id faucibus nisl tincidunt eget nullam non. Et tortor at risus viverra adipiscing at in tellus integer. Libero justo laoreet sit amet. Non nisi est sit amet. Nec nam aliquam sem et tortor consequat. Adipiscing tristique risus nec feugiat in fermentum posuere. Amet nisl suscipit adipiscing bibendum est. Mattis enim ut tellus elementum. Ullamcorper sit amet risus nullam. Duis at tellus at urna condimentum. Id donec ultrices tincidunt arcu. Laoreet sit amet cursus sit. Nibh ipsum consequat nisl vel pretium lectus. Nulla pharetra diam sit amet nisl suscipit.</p>
<p>Egestas purus viverra accumsan in nisl. In tellus integer feugiat scelerisque varius. Vitae suscipit tellus mauris a diam maecenas sed enim. Ut sem nulla pharetra diam sit amet nisl suscipit adipiscing. Nulla porttitor massa id neque aliquam vestibulum morbi blandit. Venenatis tellus in metus vulputate eu scelerisque. Fames ac turpis egestas maecenas pharetra convallis posuere. Nulla facilisi etiam dignissim diam quis enim lobortis. Mollis aliquam ut porttitor leo a diam sollicitudin tempor id. Quis auctor elit sed vulputate. Tincidunt lobortis feugiat vivamus at. Massa sapien faucibus et molestie ac. Dui nunc mattis enim ut tellus elementum sagittis vitae. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Aliquam ut porttitor leo a diam sollicitudin tempor. At augue eget arcu dictum varius duis at. Tempus quam pellentesque nec nam aliquam sem et tortor. Varius quam quisque id diam vel quam elementum pulvinar etiam. Vulputate mi sit amet mauris commodo quis imperdiet. Proin sed libero enim sed faucibus turpis.</p>
    </div>
  )
}
